/**
 * The LemLib v0.5.6 emitter. PLAN.md §3.6, §8.1.
 *
 * Only non-default params are emitted, using C++20 designated initialisers — valid in
 * the PROS toolchain LemLib targets, and far more readable than positional args.
 *
 * This lives behind a pluggable interface (see ./index.ts) because LemLib's `master` is
 * an unreleased v1.0 rewrite with no `Chassis` class. When that lands, a v1 emitter is
 * a new file rather than a rewrite of this one.
 */

import {
  MOVE_TO_POINT_DEFAULTS,
  MOVE_TO_POSE_DEFAULTS,
  SWING_TO_HEADING_DEFAULTS,
  SWING_TO_POINT_DEFAULTS,
  TURN_TO_HEADING_DEFAULTS,
  TURN_TO_POINT_DEFAULTS,
} from '../config/defaults';
import { bezierCurvature, sampleBezier } from '../model/geometry';
import type { Routine, Segment, SimTrace } from '../model/types';

const IND = '    ';

function n(v: number): string {
  // 2 dp, trailing zeros stripped. Nobody needs -23.999996.
  return String(Number(v.toFixed(2)));
}

/** Render the non-default fields of a params object as a designated initialiser. */
function paramsLiteral(params: Record<string, unknown>, defaults: Record<string, unknown>): string {
  const parts: string[] = [];
  for (const key of Object.keys(defaults)) {
    const v = params[key];
    if (v === undefined || v === defaults[key]) continue;
    if (key === 'direction') parts.push(`.direction = AngularDirection::${v}`);
    else if (typeof v === 'boolean') parts.push(`.${key} = ${v}`);
    else parts.push(`.${key} = ${n(v as number)}`);
  }
  return parts.length ? `, {${parts.join(', ')}}` : '';
}

/**
 * Chaining is set on the segment but lives in the params when emitted, matching how it
 * is written by hand.
 */
function effective(seg: Extract<Segment, { chain: unknown }>): Record<string, unknown> {
  const base = 'params' in seg ? { ...(seg.params as Record<string, unknown>) } : {};
  if (seg.chain.mode === 'chained') {
    base.minSpeed = seg.chain.minSpeed;
    base.earlyExitRange = seg.chain.earlyExitRange;
  }
  return base;
}

function assetName(name: string): string {
  const safe = name.replace(/[^A-Za-z0-9_]/g, '_');
  return `${safe}_txt`;
}

export type EmitResult = {
  code: string;
  /** Pure-pursuit path files, keyed by filename, for the `static/` directory. */
  paths: Record<string, string>;
};

export function emit(routine: Routine, trace: SimTrace | null): EmitResult {
  const lines: string[] = [];
  const paths: Record<string, string> = {};

  const total = trace ? `  ·  est. ${trace.duration.toFixed(1)} s` : '';
  lines.push(`// Generated by VEX Pathing — Override 2026-27`);
  lines.push(`// Routine: "${routine.name}"  ·  ${routine.alliance}  ·  LemLib v0.5.6${total}`);
  lines.push(`// This is a starting point. Tune on the field.`);
  lines.push('');

  const followSegs = routine.segments.filter((s) => s.kind === 'follow');
  if (followSegs.length) {
    for (const s of followSegs) {
      if (s.kind !== 'follow') continue;
      lines.push(`ASSET(${assetName(s.name)});`);
    }
    lines.push('');
  }

  lines.push('void autonomous() {');
  lines.push(`${IND}chassis.setPose(${n(routine.start.x)}, ${n(routine.start.y)}, ${n(routine.start.theta)});`);
  lines.push('');

  routine.segments.forEach((seg, i) => {
    const result = trace?.segments.find((r) => r.index === i);
    if (seg.note) lines.push(`${IND}// ${seg.note}`);

    switch (seg.kind) {
      case 'wait':
        lines.push(`${IND}pros::delay(${seg.ms});`);
        break;

      case 'action':
        for (const l of seg.code.split('\n')) lines.push(`${IND}${l}`);
        break;

      case 'moveToPoint':
        lines.push(
          `${IND}chassis.moveToPoint(${n(seg.target.x)}, ${n(seg.target.y)}, ${seg.timeout}` +
            `${paramsLiteral(effective(seg), MOVE_TO_POINT_DEFAULTS)});`,
        );
        break;

      case 'moveToPose':
        lines.push(
          `${IND}chassis.moveToPose(${n(seg.target.x)}, ${n(seg.target.y)}, ${n(seg.target.theta)}, ${seg.timeout}` +
            `${paramsLiteral(effective(seg), MOVE_TO_POSE_DEFAULTS)});`,
        );
        break;

      case 'turnToHeading':
        lines.push(
          `${IND}chassis.turnToHeading(${n(seg.theta)}, ${seg.timeout}` +
            `${paramsLiteral(effective(seg), TURN_TO_HEADING_DEFAULTS)});`,
        );
        break;

      case 'turnToPoint':
        lines.push(
          `${IND}chassis.turnToPoint(${n(seg.target.x)}, ${n(seg.target.y)}, ${seg.timeout}` +
            `${paramsLiteral(effective(seg), TURN_TO_POINT_DEFAULTS)});`,
        );
        break;

      case 'swingToHeading':
        lines.push(
          `${IND}chassis.swingToHeading(${n(seg.theta)}, DriveSide::${seg.side}, ${seg.timeout}` +
            `${paramsLiteral(effective(seg), SWING_TO_HEADING_DEFAULTS)});`,
        );
        break;

      case 'swingToPoint':
        lines.push(
          `${IND}chassis.swingToPoint(${n(seg.target.x)}, ${n(seg.target.y)}, DriveSide::${seg.side}, ${seg.timeout}` +
            `${paramsLiteral(effective(seg), SWING_TO_POINT_DEFAULTS)});`,
        );
        break;

      case 'follow': {
        const forwards = seg.forwards ? '' : ', false';
        lines.push(
          `${IND}chassis.follow(${assetName(seg.name)}, ${n(seg.lookahead)}, ${seg.timeout}${forwards});`,
        );
        paths[`${seg.name}.txt`] = emitPathFile(seg.controlPoints, routine);
        break;
      }
    }

    // Markers, then the handoff.
    if (seg.kind !== 'wait' && seg.kind !== 'action') {
      for (const m of seg.markers) {
        lines.push(`${IND}chassis.waitUntil(${n(m.atInches)});`);
        for (const l of m.code.split('\n')) lines.push(`${IND}${l}`);
      }
      if (seg.chain.mode === 'blocking') lines.push(`${IND}chassis.waitUntilDone();`);
    }

    if (result && seg.kind !== 'action') {
      const dur = (result.endT - result.startT).toFixed(2);
      const note = result.exit === 'timeout' ? ' TIMED OUT' : result.collided ? ' COLLISION' : '';
      lines.push(`${IND}// ^ ${dur}s (${result.exit})${note}`);
    }
    lines.push('');
  });

  // Trim the trailing blank line before the brace.
  while (lines.length && lines[lines.length - 1] === '') lines.pop();
  lines.push('}');

  return { code: lines.join('\n'), paths };
}

/**
 * The pure-pursuit path file. PLAN.md §3.4.
 *
 * Format confirmed by reading getData() in pursuit.cpp @ v0.5.6:
 *   - fields separated by the literal two-character delimiter ", " (comma AND space —
 *     a bare comma fails to parse)
 *   - exactly three fields: x, y, velocity
 *   - parsing stops at a line equal to "endData"
 */
export function emitPathFile(controlPoints: { x: number; y: number }[], routine: Routine): string {
  const samples = sampleBezier(controlPoints, 2);
  const maxVel = (routine.settings.drivetrain.rpm / 60) * Math.PI * routine.settings.drivetrain.wheelDiameter;

  const out = samples.map(({ p, t }) => {
    // Curvature-based taper: slower through tight curvature, capped at the drivetrain
    // maximum. LemLib treats the column as a speed cap, so a constant would work but
    // would waste time on the straights.
    const k = bezierCurvature(controlPoints, t);
    const v = Math.min(maxVel, k < 1e-6 ? maxVel : Math.sqrt(3 / k));
    return `${p.x.toFixed(3)}, ${p.y.toFixed(3)}, ${v.toFixed(3)}`;
  });
  out.push('endData');
  return out.join('\n');
}
